# Set up for npm and Composer

version: 2
updates:

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    rebase-strategy: auto
    schedule:
      interval: "daily"
      time: "04:00"
    versioning-strategy: increase

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    allow:
    - dependency-type: direct
    - dependency-type: indirect
    directory: "/"
    open-pull-requests-limit: 10
    rebase-strategy: auto
    schedule:
      interval: "daily"
      time: "04:00"
    versioning-strategy: increase
