<?php
/**
 * Block editor (gutenberg) specific functionality
 *
 * @package UnderStrap
 */


add_action( 'after_setup_theme', 'understrap_block_editor_setup' );

if ( ! function_exists( 'understrap_block_editor_setup' ) ) {

	/**
	 * Sets up our default theme support for the WordPress block editor.
	 *
	 */
	function understrap_block_editor_setup() {

		// Add support for the block editor stylesheet.
		add_theme_support( 'editor-styles' );

		// Add support for wide alignment.
		add_theme_support( 'align-wide' );

		// Grabs the autogenerated color palette that we're pulling from our compiled bootstrap stylesheets.
		$color_palette_json = wp_remote_get( get_stylesheet_directory_uri() . '/inc/editor-color-palette.json' );
		if ( ! is_wp_error( $color_palette_json ) ) {
			$color_palette_json = json_decode( $color_palette_json['body'], true );
			$color_palette      = array();
			foreach ( $color_palette_json as $key => $value ) {
				$key             = ltrim( $key, '--' );
				$color_palette[] = array(
					'name'  => $key,
					'slug'  => $key,
					'color' => $value,
				);
			}
		}

		/**
		 * Filters the default bootstrap color palette so it can be overriden by child themes or plugins when we add theme support for editor-color-palette
		 *
		 * @param array $color_palette An array of color options for the editor-color-palette setting.
		 */
		$color_palette = apply_filters( 'understrap_theme_editor_color_palette', $color_palette );

		// Register our custom colors as options in the editor.
		add_theme_support( 'editor-color-palette', $color_palette );
	}
}
